###=========================================================================
### File: Dockerfile
###
### Author(s):
###   - Enrique Fernandez <efcasado@gmail.com>
###=========================================================================
FROM python:2.7.12

# Install RabbitMQ client
RUN pip install pika
