###=========================================================================
### File: docker-compose.yml
###
### Author(s):
###   - Enrique Fernandez <efcasado@gmail.com>
###=========================================================================
version: '2'

services:
  graphite:
    image: efcasado/graphite
    ports:
      - 8080:8080
    networks:
      rabbitmq-monitoring:
        aliases:
          - graphite
  grafana:
    image: efcasado/grafana
    volumes:
      - ./volumes/grafana/var/lib/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
    networks:
      rabbitmq-monitoring:
        aliases:
          - grafana    
  
  rabbitmq:
    image: rabbitmq:3.6.5-management
    ports:
      - 8888:15672
    networks:
      rabbitmq-monitoring:
        aliases:
          - rabbitmq

  sender1:
    build: ./Dockerfiles/python
    environment:
      - "RABBITMQ_QUEUE=foo"
    volumes:
      - ./volumes/python/code:/code
    working_dir: /code
    entrypoint: python
    command: send.py
    networks:
      - rabbitmq-monitoring
    depends_on:
      - rabbitmq
    restart: always

  sender2:
    build: ./Dockerfiles/python
    environment:
      - "RABBITMQ_QUEUE=bar"
    volumes:
      - ./volumes/python/code:/code
    working_dir: /code
    entrypoint: python
    command: send.py
    networks:
      - rabbitmq-monitoring
    depends_on:
      - rabbitmq
    restart: always

  receiver:
    build: ./Dockerfiles/python
    environment:
      - "RABBITMQ_QUEUES=foo,bar"
    volumes:
      - ./volumes/python/code:/code
    working_dir: /code
    entrypoint: python
    command: receive.py
    networks:
      - rabbitmq-monitoring
    depends_on:
      - rabbitmq
    restart: always
    
  collectd:
    build: ./Dockerfiles/collectd/
    volumes:
      - ./volumes/collectd/etc/collectd:/etc/collectd
      - ./volumes/collectd/usr/share/collectd:/usr/share/collectd
    networks:
      rabbitmq-monitoring:
        aliases:
          - collectd
    depends_on:
      - graphite
      - rabbitmq

networks:
  rabbitmq-monitoring:
    driver: bridge      
